# Generated by Django 5.0.6 on 2024-06-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_manufacturer_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
